/* SAT Studio — Desmos how-to hints for Advanced Math sets (math-adv + math-adv2) */
window.SAT_DESMOS = Object.assign(window.SAT_DESMOS || {}, {
  'ADV-01': { note:'Since the bases are already the same, set the exponents equal: x+2=7. To check it in Desmos, graph y=5^(x+2) and y=5^7 and see that they cross at x=5.', latex:['y=5^(x+2)', 'y=5^7'] },
  'ADV-02': { note:'Graph y=x^2-x-12 and look at where it crosses the x-axis: at −3 and 4. The positive solution they ask for is 4.', latex:['y=x^2-x-12'] },
  'ADV-03': { note:'Graph y=x^2-6x+5; since it opens upward, the lowest point (the vertex) is at (3,−4), so the minimum value is −4.', latex:['y=x^2-6x+5'] },
  'ADV-04': { note:'Graph y=300*1.12^x and add the point (1,336): it lands right on the curve (300 plus 12%), which confirms the factor 1.12.', latex:['y=300*1.12^x', '(1,336)'] },
  'ADV-05': { note:'Graph y=(2x+3)(x-4) and y=2x^2-5x-12; if the two curves lie on top of each other, they are equivalent.', latex:['y=(2x+3)(x-4)', 'y=2x^2-5x-12'] },
  'ADV-06': { note:'Graph y=(x+4)(x-2)(x-5) and count the x-axis crossings: there are 3 (at −4, 2, and 5).', latex:['y=(x+4)(x-2)(x-5)'] },
  'ADV-07': { note:'Graph y=x^2 and y=x+6 and tap the two intersections: (−2,4) and (3,9). Careful: they ask for the greatest VALUE OF y, which is 9.', latex:['y=x^2', 'y=x+6'] },
  'ADV-08': { note:'Graph y=x^2+12x+c and let Desmos add a slider for c; move it until the parabola touches the x-axis at exactly one point (tangent): that happens at c=36.', latex:['y=x^2+12x+c'] },
  'ADV-09': { note:'Graph y=2x^2-16x+24 and locate the roots (2 and 6); add them to get 8. The axis of symmetry x=4 is the midpoint, so the sum is 2·4.', latex:['y=2x^2-16x+24'] },
  'ADV-10': { note:'Graph y=80*(1/2)^(x/6) and check it with the points (6,40) and (12,20): the mass is cut in half every 6 years.', latex:['y=80*(1/2)^(x/6)', '(6,40)', '(12,20)'] },
  'ADV-11': { note:'Graph y=(x-4)^2-9 and look at the lowest point: the vertex is at (4,−9).', latex:['y=(x-4)^2-9'] },
  'ADV-12': { note:'Graph y=9x^2+bx+4 with the b slider; raise it on the positive side until the parabola touches the x-axis just once: that happens at b=12.', latex:['y=9x^2+bx+4'] },
  'AV2-01': { note:'Since the bases are already the same, set the exponents equal: 3x=12. To check it, graph y=2^(3x) and y=2^(12) and see that they cross at x=4.', latex:['y=2^(3x)', 'y=2^(12)'] },
  'AV2-02': { note:'Graph y=x^2+2x-15 and look at the x-axis crossings: −5 and 3. The positive solution is 3.', latex:['y=x^2+2x-15'] },
  'AV2-03': { note:'Type f(x)=2x^2-3x+1 and on the line below type f(-2); Desmos shows you 15 instantly.', latex:['f(x)=2x^2-3x+1', 'f(-2)'] },
  'AV2-04': { note:'Graph y=400*0.85^x to see the decay and add the point (1,340): it lands on the curve (400 minus 15%), which confirms the factor 0.85.', latex:['y=400*0.85^x', '(1,340)'] },
  'AV2-05': { note:'Graph y=x^2-8x+11; the lowest point (the vertex) is at (4,−5), so the minimum value is −5.', latex:['y=x^2-8x+11'] },
  'AV2-06': { note:'Graph y=(x-1)(x+3)^2(x-6) and count the DISTINCT values where it meets the x-axis: there are 3 (at −3 it bounces, but it counts only once).', latex:['y=(x-1)(x+3)^2(x-6)'] },
  'AV2-07': { note:'Graph y=x^2-14x+40 and find the roots (4 and 10); multiply them to get the product 40.', latex:['y=x^2-14x+40'] },
  'AV2-08': { note:'Graph y=x^2+10x+c with the c slider; move it until the parabola touches the x-axis at exactly one point: that happens at c=25.', latex:['y=x^2+10x+c'] },
  'AV2-09': { note:'Graph y=3x^2-18x+15 and add the roots (1 and 5) to get 6. The axis of symmetry x=3 is the midpoint.', latex:['y=3x^2-18x+15'] },
  'AV2-10': { note:'Graph y=(x+2)^2-7 and look at the lowest point: the vertex is at (−2,−7).', latex:['y=(x+2)^2-7'] },
  'AV2-11': { note:'Graph y=x^2-3 and y=2x+5 and tap the intersections: at x=−2 and x=4. They ask for the greatest VALUE OF x, which is 4.', latex:['y=x^2-3', 'y=2x+5'] },
  'AV2-12': { note:'Graph y=4x^2+bx+25 with the b slider; raise it on the positive side until the parabola touches the x-axis just once: that happens at b=20.', latex:['y=4x^2+bx+25'] }
});
